# Generated by Django 5.0.1 on 2024-01-17 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authuser',
            options={'verbose_name': 'Пользователя приложения', 'verbose_name_plural': 'Пользователи приложения'},
        ),
        migrations.AlterModelOptions(
            name='followers',
            options={'verbose_name': 'Подписчика', 'verbose_name_plural': 'Подписчики'},
        ),
    ]
